#!/usr/bin/ruby

# Produce Popolo-compatible JSON for a member of the Finnish Parliament
# This should be passed either
#   * the URL to their official web page (English version), e.g.
#     http://www.eduskunta.fi/triphome/bin/hex5000.sh?hnro=261&kieli=en
#   * or the path to a locally saved copy of that page

require 'eduskunta-scraper'
require 'json'
require 'open-uri'

mp_page = ARGV[0] or abort "Usage: #{$0} <url_or_file>"
language = ARGV[1] || "EN"

puts JSON.pretty_generate( Eduskunta::Scraper.const_get(language).new(open(mp_page)).as_hash )

